language: objective-c
env:
  matrix:
    - TEST_TYPE=mobile-unit-test
    - TEST_TYPE=mobile-integration-test
  global:
    - DIRECTORY_MOBILE=client/mobile
    - PROJECT_MOBILE=mobileApp
cache:
  directories:
  - client/mobile/mobileApp/node_modules
before_install:
  - brew update
install:
  - brew reinstall flow watchman xctool
branches:
  only:
    - master
script:
- |
  if [ "$TEST_TYPE" = mobile-unit-test ]
  then
 
    cd $DIRECTORY_MOBILE/$PROJECT_MOBILE
    npm install
    flow check
    npm test
 
  elif [ "$TEST_TYPE" = mobile-integration-test ]
  then
 
    cd $DIRECTORY_MOBILE
    npm install $PROJECT_MOBILE
    (npm start > packager.log 2>&1 &)
    echo $! > packager.pid
 
    xctool \
      -project $PROJECT_MOBILE/$PROJECT_MOBILE.xcodeproj \
      -scheme $PROJECT_MOBILE -sdk iphonesimulator8.1
      test
 
    pkill -9 -F packager.pid
    cat packager.log
    rm packager.log packager.pid
 
  else
    echo "Unknown test type: $TEST_TYPE"
    exit 1
  fi